### ISSUE TITLE
Perhitungan datetime yang lebih aman

### ISSUE THREAD

**Issue by widoyo** [Ranovan7/prinus_python#3]
https://github.com/Ranovan7/prinus_python/blob/72b0a8b9f4aa79af41599c30201b685a494e021a/apps/command.py#L51

Saya gunakan `datetime.timedelta()`
Saya juga koreksi code jadi lebih pendek, ternary operator gaya python, menggunakan `and` dan `or`

```
def getstarttime(time):
  res = time.hour < 7 and (res - datetime.timedelta(days=1)) or res
  return res.replace(hour=7, minute=0, second=0)
```

**Comment by Ranovan7** [comment]
fix #3 on commit 
107b6e1
